/**
 * Emoji-Palette mit Suchbegriffen (DE/EN)
 * Format: [emoji, "keyword1 keyword2 ..."]
 */
export const EMOJI_DATA = [
  ['😀', 'grin lachen happy smile'],
  ['😃', 'smile lachen happy'],
  ['😄', 'grin happy smile'],
  ['😁', 'grin beaming strahlen'],
  ['😅', 'sweat schweiß nervös'],
  ['😆', 'squinting squint'],
  ['😇', 'angel engel süß'],
  ['🙂', 'smile leicht'],
  ['🙃', 'upside down kopf'],
  ['😉', 'wink zwinkern'],
  ['😊', 'blush erröten freundlich'],
  ['😋', 'yum lecker essen'],
  ['😌', 'relieved erleichtert'],
  ['😍', 'heart eyes verliebt'],
  ['🥰', 'love liebe herz'],
  ['😘', 'kiss kuss'],
  ['😗', 'kissing kuss'],
  ['😙', 'kissing smile'],
  ['😚', 'kissing closed'],
  ['😛', 'tongue zunge'],
  ['😜', 'wink tongue zwinkern'],
  ['😝', 'squinting tongue'],
  ['😞', 'disappointed enttäuscht'],
  ['😟', 'worried besorgt'],
  ['😠', 'angry wütend'],
  ['😡', 'rage wut'],
  ['😢', 'cry weinen traurig'],
  ['😣', 'persevere durchhalten'],
  ['😤', 'triumph triumph'],
  ['😥', 'sad disappointed'],
  ['😦', 'frown runzel'],
  ['😧', 'anguished gequält'],
  ['😨', 'fear angst'],
  ['😩', 'weary müde'],
  ['😪', 'sleepy schläfrig'],
  ['😫', 'tired erschöpft'],
  ['😬', 'grimace grimasse'],
  ['😭', 'sob weinen'],
  ['😮', 'open mouth oh'],
  ['😯', 'hushed überrascht'],
  ['😰', 'anxious ängstlich'],
  ['😱', 'scream schrei'],
  ['😲', 'astonished erstaunt'],
  ['😳', 'flushed errötet'],
  ['😴', 'sleeping schlafen'],
  ['😵', 'dizzy schwindlig'],
  ['😶', 'speechless sprachlos'],
  ['😷', 'mask maske krank'],
  ['🤒', 'thermometer fieber'],
  ['🤕', 'head bandage kopf'],
  ['🤢', 'nauseated übel'],
  ['🤣', 'rofl lachen'],
  ['🤤', 'drooling sabbern'],
  ['🤥', 'lying lügen'],
  ['🤧', 'sneezing niesen'],
  ['🤨', 'raised eyebrow'],
  ['🤩', 'star struck sterne'],
  ['🤪', 'zany verrückt'],
  ['🤫', 'shush pst'],
  ['🤬', 'cursing fluchen'],
  ['🤭', 'hand mouth'],
  ['🤮', 'vomit kotzen'],
  ['🤯', 'exploding head'],
  ['🤰', 'pregnant schwanger'],
  ['🤱', 'breastfeeding stillen'],
  ['🤲', 'palms up'],
  ['🤳', 'selfie'],
  ['🤴', 'prince prinz'],
  ['🤵', 'tuxedo anzug'],
  ['🤶', 'mrs claus weihnachten'],
  ['🤷', 'shrug schulterzucken'],
  ['🤸', 'cartwheel rad'],
  ['🤹', 'juggling jonglieren'],
  ['🤺', 'fencing fechten'],
  ['🤼', 'wrestling ringen'],
  ['🤽', 'water polo'],
  ['🤾', 'handball'],
  ['🥀', 'wilted welk'],
  ['🥁', 'drum trommel'],
  ['🥂', 'champagne'],
  ['🥃', 'whisky'],
  ['🥄', 'spoon löffel'],
  ['🥅', 'goal tor'],
  ['🥇', 'gold goldmedaille'],
  ['🥈', 'silver silber'],
  ['🥉', 'bronze bronze'],
  ['🥊', 'boxing boxen'],
  ['🥋', 'martial arts'],
  ['🥌', 'curling'],
  ['🥍', 'lacrosse'],
  ['🥎', 'softball'],
  ['🥏', 'frisbee'],
  ['🥐', 'croissant'],
  ['🥑', 'avocado'],
  ['🥒', 'cucumber gurke'],
  ['🥓', 'bacon speck'],
  ['🥔', 'potato kartoffel'],
  ['🥕', 'carrot karotte'],
  ['🥖', 'baguette brot'],
  ['🥗', 'salad salat'],
  ['🥘', 'paella'],
  ['🥙', 'kebab'],
  ['🥚', 'egg ei'],
  ['🥛', 'milk milch'],
  ['🥜', 'peanuts erdnüsse'],
  ['🥝', 'kiwi'],
  ['🥞', 'pancakes pfannkuchen'],
  ['🥟', 'dumpling'],
  ['🥠', 'fortune cookie'],
  ['🥡', 'takeout'],
  ['🥢', 'chopsticks stäbchen'],
  ['🥣', 'bowl schüssel'],
  ['🥤', 'cup trinkbecher'],
  ['🥥', 'coconut kokos'],
  ['🥦', 'broccoli'],
  ['🥧', 'pie kuchen'],
  ['🥨', 'pretzel brezel'],
  ['🥩', 'steak'],
  ['🥪', 'sandwich'],
  ['👍', 'thumbs up daumen'],
  ['👎', 'thumbs down'],
  ['👏', 'clap klatschen'],
  ['🙌', 'raised hands hände'],
  ['👐', 'open hands'],
  ['🤝', 'handshake händedruck'],
  ['🙏', 'pray beten danke'],
  ['✌️', 'peace victory sieg'],
  ['🤞', 'fingers crossed'],
  ['🤟', 'love you'],
  ['🤘', 'rock horns'],
  ['🤙', 'call me'],
  ['👌', 'ok perfekt'],
  ['🤌', 'pinched'],
  ['🤏', 'pinching'],
  ['✋', 'hand hand hoch'],
  ['🤚', 'raised back'],
  ['🖐️', 'raised fingers'],
  ['🖖', 'vulcan spock'],
  ['👋', 'wave winken'],
  ['🤚', 'back hand'],
  ['💪', 'muscle kraft stark'],
  ['🦾', 'mechanical arm'],
  ['🦿', 'mechanical leg'],
  ['🦵', 'leg bein'],
  ['🦶', 'foot fuß'],
  ['👂', 'ear ohr'],
  ['🦻', 'hearing aid'],
  ['👃', 'nose nase'],
  ['🧠', 'brain gehirn'],
  ['🫀', 'heart organ'],
  ['🫁', 'lungs lunge'],
  ['🦷', 'tooth zahn'],
  ['🦴', 'bone knochen'],
  ['👀', 'eyes augen'],
  ['👁️', 'eye auge'],
  ['👅', 'tongue zunge'],
  ['👄', 'mouth mund'],
  ['💋', 'kiss kuss'],
  ['🩸', 'blood blut'],
  ['❤️', 'heart herz liebe'],
  ['🧡', 'orange heart'],
  ['💛', 'yellow heart'],
  ['💚', 'green heart'],
  ['💙', 'blue heart'],
  ['💜', 'purple heart'],
  ['🖤', 'black heart'],
  ['🤍', 'white heart'],
  ['🤎', 'brown heart'],
  ['💔', 'broken heart'],
  ['❣️', 'heart exclamation'],
  ['💕', 'two hearts'],
  ['💞', 'revolving hearts'],
  ['💓', 'beating heart'],
  ['💗', 'growing heart'],
  ['💖', 'sparkling heart'],
  ['💘', 'cupid herz'],
  ['💝', 'gift heart'],
  ['💟', 'heart decoration'],
  ['☮️', 'peace friedenszeichen'],
  ['✝️', 'cross kreuz'],
  ['☪️', 'star crescent'],
  ['🕉️', 'om'],
  ['☸️', 'wheel'],
  ['✡️', 'star david'],
  ['🔯', 'star six'],
  ['🕎', 'menorah'],
  ['☯️', 'yin yang'],
  ['☦️', 'orthodox cross'],
  ['🛐', 'place worship'],
  ['⛎', 'ophiuchus'],
  ['♈', 'aries widder'],
  ['♉', 'taurus stier'],
  ['♊', 'gemini zwillinge'],
  ['♋', 'cancer krebs'],
  ['♌', 'leo löwe'],
  ['♍', 'virgo jungfrau'],
  ['♎', 'libra waage'],
  ['♏', 'scorpio skorpion'],
  ['♐', 'sagittarius schütze'],
  ['♑', 'capricorn steinbock'],
  ['♒', 'aquarius wassermann'],
  ['♓', 'pisces fische'],
  ['🆔', 'id ausweis'],
  ['⚛️', 'atom'],
  ['🉑', 'accept'],
  ['☢️', 'radioactive'],
  ['☣️', 'bio'],
  ['📴', 'mobile off'],
  ['📳', 'vibration'],
  ['🈶', 'ideograph advantage'],
  ['🈚', 'ideograph secret'],
  ['🈸', 'ideograph apply'],
  ['🈺', 'ideograph open'],
  ['🈷️', 'ideograph month'],
  ['✴️', 'eight pointed'],
  ['🆚', 'vs versus'],
  ['💮', 'white flower'],
  ['🉐', 'ideograph bargain'],
  ['㊙️', 'secret geheim'],
  ['㊗️', 'congratulations'],
  ['🈴', 'ideograph accept'],
  ['🈵', 'ideograph full'],
  ['🈹', 'ideograph discount'],
  ['🈲', 'ideograph prohibit'],
  ['🅰️', 'a blut'],
  ['🅱️', 'b blut'],
  ['🆎', 'ab blut'],
  ['🆑', 'cl'],
  ['🅾️', 'o'],
  ['🆘', 'sos hilfe'],
  ['❌', 'x cross falsch'],
  ['⭕', 'o circle'],
  ['🛑', 'stop halt'],
  ['⛔', 'no entry verboten'],
  ['📛', 'name badge'],
  ['🚫', 'prohibited verboten'],
  ['💯', 'hundred 100 perfekt'],
  ['💢', 'anger wut'],
  ['💥', 'collision boom'],
  ['💫', 'dizzy schwindlig'],
  ['💦', 'sweat schweiß'],
  ['💨', 'dash wind'],
  ['🕳️', 'hole loch'],
  ['💣', 'bomb bombe'],
  ['💬', 'speech bubble'],
  ['👁️‍🗨️', 'eye speech'],
  ['🗨️', 'left speech'],
  ['🗯️', 'right anger'],
  ['💭', 'thought bubble'],
  ['💤', 'zzz schlafen'],
  ['🔥', 'fire flamme heiß'],
  ['✨', 'sparkles glitzer'],
  ['⭐', 'star stern'],
  ['🌟', 'glowing star'],
  ['💥', 'collision'],
  ['❗', 'exclamation'],
  ['❓', 'question frage'],
  ['‼️', 'double exclamation'],
  ['⁉️', 'exclamation question'],
  ['🔅', 'dim'],
  ['🔆', 'bright'],
  ['〽️', 'part alternation'],
  ['⚠️', 'warning warnung'],
  ['🚸', 'children'],
  ['🔱', 'trident'],
  ['⚜️', 'fleur de lis'],
  ['🔰', 'beginner'],
  ['♻️', 'recycle recycling'],
  ['✅', 'check richtig'],
  ['🈯', 'ideograph correct'],
  ['💹', 'chart increasing'],
  ['❇️', 'sparkle'],
  ['✳️', 'eight spoked'],
  ['❎', 'cross mark'],
  ['🌐', 'globe welt'],
  ['💠', 'diamond dot'],
  ['Ⓜ️', 'm'],
  ['🌀', 'cyclone wirbel'],
  ['💤', 'zzz'],
  ['🏧', 'atm'],
  ['🚾', 'wc toilette'],
  ['🅿️', 'parking parken'],
  ['🈳', 'ideograph empty'],
  ['🈂️', 'ideograph service'],
  ['🛂', 'passport control'],
  ['🛃', 'customs zoll'],
  ['🛅', 'baggage'],
  ['🚹', 'men männer'],
  ['🚺', 'women frauen'],
  ['🚼', 'baby'],
  ['⚧️', 'transgender'],
  ['🚻', 'restroom toilette'],
  ['🚮', 'litter müll'],
  ['🎵', 'music note'],
  ['🎶', 'music notes'],
  ['🏳️', 'white flag'],
  ['🏴', 'black flag'],
  ['🏁', 'checkered flag'],
  ['🚩', 'triangular flag'],
  ['🎌', 'crossed flags'],
  ['🏴‍☠️', 'pirate'],
  ['🇩🇪', 'germany deutschland'],
  ['🇦🇹', 'austria österreich'],
  ['🇨🇭', 'switzerland schweiz'],
  ['🇺🇸', 'usa amerika'],
  ['🇬🇧', 'uk england'],
  ['🇫🇷', 'france frankreich'],
  ['🇪🇸', 'spain spanien'],
  ['🇮🇹', 'italy italien'],
  ['🇯🇵', 'japan'],
  ['🇨🇳', 'china'],
  ['🐶', 'dog hund'],
  ['🐱', 'cat katze'],
  ['🐭', 'mouse maus'],
  ['🐹', 'hamster'],
  ['🐰', 'rabbit hase'],
  ['🦊', 'fox fuchs'],
  ['🐻', 'bear bär'],
  ['🐼', 'panda'],
  ['🐨', 'koala'],
  ['🐯', 'tiger'],
  ['🦁', 'lion löwe'],
  ['🐮', 'cow kuh'],
  ['🐷', 'pig schwein'],
  ['🐸', 'frog frosch'],
  ['🐵', 'monkey affe'],
  ['🐔', 'chicken huhn'],
  ['🐧', 'penguin pinguin'],
  ['🐦', 'bird vogel'],
  ['🐤', 'baby chick'],
  ['🦆', 'duck ente'],
  ['🦅', 'eagle adler'],
  ['🦉', 'owl eule'],
  ['🦇', 'bat fledermaus'],
  ['🐺', 'wolf'],
  ['🐗', 'boar eber'],
  ['🐴', 'horse pferd'],
  ['🦄', 'unicorn einhorn'],
  ['🐝', 'bee biene'],
  ['🐛', 'bug käfer'],
  ['🦋', 'butterfly schmetterling'],
  ['🐌', 'snail schnecke'],
  ['🐞', 'ladybug marienkäfer'],
  ['🐜', 'ant ameise'],
  ['🦟', 'mosquito mücke'],
  ['🦗', 'cricket grille'],
  ['🕷️', 'spider spinne'],
  ['🦂', 'scorpion skorpion'],
  ['🍎', 'apple apfel'],
  ['🍐', 'pear birne'],
  ['🍊', 'orange'],
  ['🍋', 'lemon zitrone'],
  ['🍌', 'banana banane'],
  ['🍉', 'watermelon wassermelone'],
  ['🍇', 'grapes trauben'],
  ['🍓', 'strawberry erdbeere'],
  ['🫐', 'blueberries'],
  ['🍈', 'melone'],
  ['🍒', 'cherries kirschen'],
  ['🍑', 'peach pfirsich'],
  ['🥭', 'mango'],
  ['🍍', 'pineapple ananas'],
  ['🥥', 'coconut kokos'],
  ['🥑', 'avocado'],
  ['🍆', 'eggplant aubergine'],
  ['🥔', 'potato kartoffel'],
  ['🥕', 'carrot karotte'],
  ['🌽', 'corn mais'],
  ['🌶️', 'pepper paprika'],
  ['🥒', 'cucumber gurke'],
  ['🥬', 'leafy green'],
  ['🥦', 'broccoli'],
  ['🍄', 'mushroom pilz'],
  ['🥜', 'peanuts erdnüsse'],
  ['🍞', 'bread brot'],
  ['🥐', 'croissant'],
  ['🥖', 'baguette'],
  ['🥨', 'pretzel brezel'],
  ['🥯', 'bagel'],
  ['🥞', 'pancakes pfannkuchen'],
  ['🧀', 'cheese käse'],
  ['🍖', 'meat fleisch'],
  ['🍗', 'poultry'],
  ['🥩', 'steak'],
  ['🍕', 'pizza'],
  ['🌭', 'hotdog'],
  ['🥪', 'sandwich'],
  ['🌮', 'taco'],
  ['🌯', 'burrito'],
  ['🥙', 'kebab'],
  ['🍳', 'egg ei'],
  ['🥘', 'paella'],
  ['🍲', 'pot'],
  ['🥣', 'bowl'],
  ['🥗', 'salad salat'],
  ['🍿', 'popcorn'],
  ['🧈', 'butter butter'],
  ['🍱', 'bento'],
  ['🍘', 'rice cracker'],
  ['🍙', 'rice ball'],
  ['🍚', 'rice reis'],
  ['🍛', 'curry'],
  ['🍜', 'ramen'],
  ['🍝', 'spaghetti'],
  ['🍠', 'sweet potato'],
  ['🍢', 'oden'],
  ['🍣', 'sushi'],
  ['🍤', 'shrimp'],
  ['🍥', 'fish cake'],
  ['🥮', 'mooncake'],
  ['🍡', 'dango'],
  ['🥟', 'dumpling'],
  ['🥠', 'fortune cookie'],
  ['🥡', 'takeout'],
  ['🍦', 'ice cream eis'],
  ['🍧', 'shaved ice'],
  ['🍨', 'ice cream'],
  ['🍩', 'donut'],
  ['🍪', 'cookie keks'],
  ['🎂', 'cake kuchen geburtstag'],
  ['🍰', 'cake kuchen'],
  ['🧁', 'cupcake'],
  ['🥧', 'pie'],
  ['🍫', 'chocolate schokolade'],
  ['🍬', 'candy süßigkeit'],
  ['🍭', 'lollipop lolli'],
  ['🍮', 'custard'],
  ['🍯', 'honey honig'],
  ['🍼', 'baby bottle'],
  ['☕', 'coffee kaffee'],
  ['🫖', 'teapot'],
  ['🍵', 'tea tee'],
  ['🍶', 'sake'],
  ['🍾', 'champagne'],
  ['🍷', 'wine wein'],
  ['🍸', 'cocktail'],
  ['🍹', 'tropical drink'],
  ['🍺', 'beer bier'],
  ['🍻', 'beers prost'],
  ['🥂', 'champagne prost'],
  ['🥃', 'whisky'],
  ['🥤', 'cup trinken'],
  ['🧃', 'juice box'],
  ['🧋', 'bubble tea'],
  ['🧊', 'ice eis'],
  ['⚽', 'soccer fußball'],
  ['🏀', 'basketball'],
  ['🏈', 'football american'],
  ['⚾', 'baseball'],
  ['🥎', 'softball'],
  ['🎾', 'tennis'],
  ['🏐', 'volleyball'],
  ['🏉', 'rugby'],
  ['🥏', 'frisbee'],
  ['🎱', 'pool billard'],
  ['🪀', 'yo-yo'],
  ['🏓', 'ping pong'],
  ['🏸', 'badminton'],
  ['🏒', 'hockey'],
  ['🏑', 'field hockey'],
  ['🥍', 'lacrosse'],
  ['🏏', 'cricket'],
  ['🪃', 'boomerang'],
  ['🥅', 'goal tor'],
  ['⛳', 'golf'],
  ['🪁', 'kite drachen'],
  ['🏹', 'bow bogen'],
  ['🎣', 'fishing angeln'],
  ['🤿', 'diving tauchen'],
  ['🥊', 'boxing boxen'],
  ['🎽', 'running'],
  ['🛹', 'skateboard'],
  ['🥌', 'curling'],
  ['🎿', 'ski skifahren'],
  ['⛷️', 'skier'],
  ['🏂', 'snowboard'],
  ['🪂', 'parachute'],
  ['🏋️', 'weightlifting'],
  ['🤸', 'gymnastics'],
  ['⛹️', 'basketball'],
  ['🤺', 'fencing'],
  ['🤾', 'handball'],
  ['🤽', 'water polo'],
  ['🏇', 'horse racing'],
  ['🏊', 'swimming schwimmen'],
  ['🚣', 'rowing rudern'],
  ['🧗', 'climbing klettern'],
  ['🚴', 'cycling radfahren'],
  ['🚵', 'mountain biking'],
  ['🎯', 'target ziel'],
  ['🎱', 'pool'],
  ['🎳', 'bowling'],
  ['🎮', 'video game spiel'],
  ['🎰', 'slot machine'],
  ['🎲', 'dice würfel'],
  ['🧩', 'puzzle puzzle'],
  ['♟️', 'chess schach'],
  ['🃏', 'joker karte'],
  ['🀄', 'mahjong'],
  ['🎭', 'theater theater'],
  ['🖼️', 'frame bild'],
  ['🎨', 'art kunst'],
  ['🧵', 'thread faden'],
  ['🪡', 'sewing nähen'],
  ['🧶', 'yarn wolle'],
  ['🎪', 'circus zirkus'],
  ['🎬', 'movie film'],
  ['🎤', 'microphone mikrofon'],
  ['🎧', 'headphones kopfhörer'],
  ['🎼', 'music sheet'],
  ['🎹', 'piano'],
  ['🥁', 'drum trommel'],
  ['🎷', 'saxophone'],
  ['🎺', 'trumpet'],
  ['🪗', 'accordion'],
  ['🎸', 'guitar gitarre'],
  ['🪕', 'banjo'],
  ['🎻', 'violin geige'],
  ['🪕', 'banjo'],
  ['🎲', 'dice würfel'],
  ['♠️', 'spade pik'],
  ['♥️', 'heart herz'],
  ['♦️', 'diamond karo'],
  ['♣️', 'club kreuz'],
  ['🃏', 'joker'],
  ['🀄', 'mahjong'],
  ['🎴', 'flower cards'],
  ['🎭', 'performing arts'],
  ['🖼️', 'framed picture'],
  ['🎨', 'artist palette'],
  ['🧵', 'thread'],
  ['🪡', 'sewing needle'],
  ['🧶', 'yarn'],
  ['🚗', 'car auto'],
  ['🚕', 'taxi'],
  ['🚙', 'suv'],
  ['🚌', 'bus'],
  ['🚎', 'trolleybus'],
  ['🏎️', 'race car'],
  ['🚓', 'police'],
  ['🚑', 'ambulance'],
  ['🚒', 'fire truck'],
  ['🚐', 'minibus'],
  ['🛻', 'pickup'],
  ['🚚', 'truck lkw'],
  ['🚛', 'articulated lorry'],
  ['🚜', 'tractor traktor'],
  ['🏍️', 'motorcycle motorrad'],
  ['🛵', 'scooter'],
  ['🚲', 'bicycle fahrrad'],
  ['🛴', 'kick scooter'],
  ['🛹', 'skateboard'],
  ['🚏', 'bus stop'],
  ['🛣️', 'motorway'],
  ['🛤️', 'railway'],
  ['🛢️', 'oil'],
  ['⛽', 'fuel tankstelle'],
  ['🛞', 'wheel'],
  ['🚨', 'police light'],
  ['🚥', 'traffic light ampel'],
  ['🚦', 'vertical light'],
  ['🛑', 'stop halt'],
  ['🚧', 'construction baustelle'],
  ['⚓', 'anchor anker'],
  ['🛶', 'canoe kanu'],
  ['⛵', 'sailboat segelboot'],
  ['🛳️', 'passenger ship'],
  ['⛴️', 'ferry fähre'],
  ['🛥️', 'motor boat'],
  ['🚢', 'ship schiff'],
  ['✈️', 'airplane flugzeug'],
  ['🛩️', 'small plane'],
  ['🛫', 'departure'],
  ['🛬', 'arrival'],
  ['🪂', 'parachute'],
  ['💺', 'seat sitz'],
  ['🚁', 'helicopter'],
  ['🚟', 'suspension railway'],
  ['🚠', 'mountain cable'],
  ['🚡', 'aerial tramway'],
  ['🛰️', 'satellite'],
  ['🚀', 'rocket rakete'],
  ['🛸', 'ufo'],
  ['⏰', 'alarm wecker'],
  ['⏱️', 'stopwatch'],
  ['⏲️', 'timer'],
  ['🕰️', 'mantelpiece clock'],
  ['🕛', 'twelve oclock'],
  ['🕧', 'twelve thirty'],
  ['🕐', 'one oclock'],
  ['🕜', 'one thirty'],
  ['🕑', 'two oclock'],
  ['🕝', 'two thirty'],
  ['🕒', 'three oclock'],
  ['🕞', 'three thirty'],
  ['🕓', 'four oclock'],
  ['🕟', 'four thirty'],
  ['🕔', 'five oclock'],
  ['🕠', 'five thirty'],
  ['🕕', 'six oclock'],
  ['🕡', 'six thirty'],
  ['🕖', 'seven oclock'],
  ['🕢', 'seven thirty'],
  ['🕗', 'eight oclock'],
  ['🕣', 'eight thirty'],
  ['🕘', 'nine oclock'],
  ['🕤', 'nine thirty'],
  ['🕙', 'ten oclock'],
  ['🕥', 'ten thirty'],
  ['🕚', 'eleven oclock'],
  ['🕦', 'eleven thirty'],
  ['🌑', 'new moon'],
  ['🌒', 'waxing crescent'],
  ['🌓', 'first quarter'],
  ['🌔', 'waxing gibbous'],
  ['🌕', 'full moon'],
  ['🌖', 'waning gibbous'],
  ['🌗', 'last quarter'],
  ['🌘', 'waning crescent'],
  ['🌙', 'crescent moon'],
  ['🌚', 'new moon face'],
  ['🌛', 'first quarter face'],
  ['🌜', 'last quarter face'],
  ['🌡️', 'thermometer'],
  ['☀️', 'sun sonne'],
  ['🌝', 'full moon face'],
  ['🌞', 'sun with face'],
  ['⭐', 'star stern'],
  ['🌟', 'glowing star'],
  ['✨', 'sparkles glitzer'],
  ['💫', 'dizzy'],
  ['🌠', 'shooting star'],
  ['🌌', 'milky way'],
  ['☁️', 'cloud wolke'],
  ['⛅', 'sun behind cloud'],
  ['⛈️', 'storm'],
  ['🌤️', 'sun behind small cloud'],
  ['🌥️', 'sun behind large cloud'],
  ['🌦️', 'sun behind rain'],
  ['🌧️', 'rain regen'],
  ['🌨️', 'snow cloud'],
  ['🌩️', 'lightning blitz'],
  ['🌪️', 'tornado'],
  ['🌫️', 'fog nebel'],
  ['🌬️', 'wind wind'],
  ['🌀', 'cyclone'],
  ['🌈', 'rainbow regenbogen'],
  ['🌂', 'closed umbrella'],
  ['☂️', 'umbrella schirm'],
  ['☔', 'umbrella rain'],
  ['⛱️', 'umbrella ground'],
  ['⚡', 'lightning blitz'],
  ['❄️', 'snow schnee'],
  ['☃️', 'snowman schneemann'],
  ['⛄', 'snowman without snow'],
  ['☄️', 'comet'],
  ['🔥', 'fire feuer'],
  ['💧', 'droplet tropfen'],
  ['🌊', 'wave welle'],
  ['🎄', 'christmas weihnachten'],
  ['🎃', 'halloween kürbis'],
  ['🎆', 'fireworks'],
  ['🎇', 'sparkler'],
  ['🧨', 'firecracker'],
  ['✨', 'sparkles'],
  ['🎈', 'balloon luftballon'],
  ['🎉', 'party party feier'],
  ['🎊', 'confetti'],
  ['🎋', 'tanabata'],
  ['🎍', 'pine decoration'],
  ['🎎', 'japanese dolls'],
  ['🎏', 'carp streamer'],
  ['🎐', 'wind chime'],
  ['🎑', 'moon viewing'],
  ['🧧', 'red envelope'],
  ['🎀', 'ribbon schleife'],
  ['🎁', 'gift geschenk'],
  ['🎗️', 'reminder ribbon'],
  ['🎖️', 'military medal'],
  ['🏆', 'trophy pokal'],
  ['🏅', 'medal medaille'],
  ['🥇', '1st gold'],
  ['🥈', '2nd silver'],
  ['🥉', '3rd bronze'],
  ['⚽', 'soccer ball'],
  ['⚾', 'baseball'],
  ['🥏', 'frisbee'],
  ['🎾', 'tennis'],
  ['🎱', 'pool'],
  ['🏀', 'basketball'],
  ['🏐', 'volleyball'],
  ['🏈', 'football'],
  ['🏉', 'rugby'],
  ['🎿', 'ski'],
  ['🛷', 'sled'],
  ['🥌', 'curling stone'],
  ['🎯', 'target'],
  ['🪀', 'yo-yo'],
  ['🪁', 'kite'],
  ['🎣', 'fishing'],
  ['🤿', 'diving mask'],
  ['🎽', 'running shirt'],
  ['🎽', 'running shirt'],
  ['🛹', 'skateboard'],
  ['🥍', 'lacrosse'],
  ['🏒', 'hockey'],
  ['🏑', 'field hockey'],
  ['🥍', 'lacrosse'],
  ['⛳', 'golf'],
  ['🪁', 'kite'],
  ['🏹', 'bow and arrow'],
  ['🎣', 'fishing pole'],
  ['🤿', 'diving mask'],
  ['🥊', 'boxing glove'],
  ['🎽', 'running shirt'],
  ['🛹', 'skateboard'],
  ['🥌', 'curling stone'],
  ['🎿', 'ski'],
  ['⛷️', 'skier'],
  ['🏂', 'snowboarder'],
  ['🪂', 'parachute'],
  ['🏋️', 'weight lifter'],
  ['🤸', 'gymnast'],
  ['⛹️', 'person bouncing'],
  ['🤺', 'fencer'],
  ['🤾', 'handball'],
  ['🤽', 'water polo'],
  ['🏇', 'horse racing'],
  ['🏊', 'swimmer'],
  ['🚣', 'rowboat'],
  ['🧗', 'climber'],
  ['🚴', 'cyclist'],
  ['🚵', 'mountain biker'],
  ['🎪', 'circus tent'],
  ['🎭', 'performing arts'],
  ['🎨', 'artist palette'],
  ['🎬', 'clapper'],
  ['🎤', 'microphone'],
  ['🎧', 'headphone'],
  ['🎼', 'musical score'],
  ['🎹', 'musical keyboard'],
  ['🥁', 'drum'],
  ['🎷', 'saxophone'],
  ['🎺', 'trumpet'],
  ['🎸', 'guitar'],
  ['🪕', 'banjo'],
  ['🎻', 'violin'],
  ['🪗', 'accordion'],
  ['🎲', 'game die'],
  ['♟️', 'chess pawn'],
  ['🃏', 'joker'],
  ['🀄', 'mahjong'],
  ['🎴', 'flower playing'],
];

export function searchEmojis(query, limit = 120) {
  const q = (query || '').toString().trim().toLowerCase();
  if (!q) return EMOJI_DATA.slice(0, limit);
  const words = q.split(/\s+/).filter(Boolean);
  return EMOJI_DATA.filter(([emoji, keywords]) =>
    words.some((w) => keywords.toLowerCase().includes(w))
  ).slice(0, limit);
}
